#!/usr/bin/env bash
# Store a secret you were given (WorkOS, Stripe) without it touching your
# shell history, the screen, git, or Terraform state. The value is read with
# hidden input and sent from a private temporary file.
#
# Usage:
#   scripts/put-secret.sh staging workos-api-key
#   scripts/put-secret.sh production stripe-secret-key
set -euo pipefail

ENV="${1:-}"
NAME="${2:-}"
[[ "$ENV" == "staging" || "$ENV" == "production" ]] && [[ -n "$NAME" ]] \
  || { echo "usage: $0 staging|production SECRET_NAME" >&2; exit 2; }
REGION="${AWS_REGION:-us-east-1}"

read -rsp "Value for levi/$ENV/$NAME (input hidden): " VALUE
echo
[[ -n "$VALUE" ]] || { echo "empty value; nothing stored" >&2; exit 1; }

# Catch the classic mistakes: live keys in staging, test keys in production.
case "$NAME" in
  stripe-secret-key)
    if [[ "$ENV" == "production" && ! "$VALUE" =~ ^(sk|rk)_live_ ]]; then echo "production needs a live key (rk_live_... preferred)" >&2; exit 1; fi
    if [[ "$ENV" == "staging" && ! "$VALUE" =~ ^(sk|rk)_test_ ]]; then echo "staging needs a test-mode key (rk_test_... or sk_test_...)" >&2; exit 1; fi
    ;;
  stripe-webhook-secret)
    [[ "$VALUE" =~ ^whsec_ ]] || { echo "webhook signing secrets start with whsec_" >&2; exit 1; } ;;
  workos-api-key)
    [[ "$VALUE" =~ ^sk_ ]] || { echo "WorkOS API keys start with sk_" >&2; exit 1; } ;;
  api-key-pepper)
    echo "api-key-pepper is generated by scripts/generate-secrets.sh; refusing to overwrite" >&2; exit 1 ;;
esac

TMP="$(mktemp)"
chmod 600 "$TMP"
trap 'rm -f "$TMP"' EXIT
printf '%s' "$VALUE" > "$TMP"
unset VALUE
aws secretsmanager put-secret-value --region "$REGION" --secret-id "levi/$ENV/$NAME" \
  --secret-string "file://$TMP" >/dev/null
echo "stored levi/$ENV/$NAME (redeploy the services that use it)"
